**numpy basic**

**basic array creation**


In [2]:
import numpy as np 


In [2]:
arr = np.array([ 1,2,4,5,6,7])
arr

array([1, 2, 4, 5, 6, 7])

In [3]:
a= [1,3,4,5,6,7,8.8]
a

[1, 3, 4, 5, 6, 7, 8.8]

In [4]:
np.array(a)

array([1. , 3. , 4. , 5. , 6. , 7. , 8.8])

In [5]:
arr = np.array([[1,2,3,45],[5,6,7,89],[2,4,6,8]])
arr

array([[ 1,  2,  3, 45],
       [ 5,  6,  7, 89],
       [ 2,  4,  6,  8]])

**array geberation function**

In [6]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a_ = np.zeros((6,6))
a_

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
a_ = np.ones((2,3,3))
a_

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
arr = np.linspace(1,32,12)

arr

array([ 1.        ,  3.81818182,  6.63636364,  9.45454545, 12.27272727,
       15.09090909, 17.90909091, 20.72727273, 23.54545455, 26.36363636,
       29.18181818, 32.        ])

**Random generation function**

In [9]:
np.random.rand(10) # range from 0 to 1

array([0.12702617, 0.38381618, 0.82240279, 0.83064983, 0.20902241,
       0.60095775, 0.68164655, 0.29801807, 0.51387972, 0.29632587])

In [12]:
np.random.randn(10) #range from -3 to 3

array([ 0.05727001,  2.48547149,  0.30878958,  0.31234568, -0.49401225,
        0.42582726, -1.02434658, -0.38628479, -0.36012174,  0.95742775])

In [14]:
np.random.randint(12, 20,5)

array([15, 13, 17, 14, 16])

In [17]:
arr = np.array([[1,2,3],[5,6,7],[2,4,6]])
arr

array([[1, 2, 3],
       [5, 6, 7],
       [2, 4, 6]])

In [22]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.dtype

dtype('int32')

**Array Methods**

In [23]:
arr

array([[1, 2, 3],
       [5, 6, 7],
       [2, 4, 6]])

In [24]:
arr.min()

1

In [25]:
arr.max()

7

In [26]:
arr.mean()

4.0

In [27]:
arr.sum()

36

In [30]:
np.sum(arr,axis= 0) # columns wise summation 

array([ 8, 12, 16])

In [24]:
np.sum(arr,axis = 1) # rowwise summation 

array([ 6, 18, 12])

In [25]:
arr.std()

2.0

In [26]:
arr.argmax() # it give index of max value 

5

In [27]:
arr.min()

1

**Reshaping and resizing**

In [28]:
arr= np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
arr= np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
import numpy as np

In [31]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
for i in range(len(arr)):        # using the concept of for lop to check it is work or not ,ofcourse it work same as list
    print(f"{arr[i]}")

11
12
13
14
15
16
17
18
19
20


In [33]:
arr[3:6]  # these are indexes

array([14, 15, 16])

In [34]:
arr[:7]     # default from starting

array([11, 12, 13, 14, 15, 16, 17])

In [35]:
arr[:] # default   from starting to end 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
arr[::2]

array([11, 13, 15, 17, 19])

In [37]:
arr[3]

14

**NUMPY INDEXING AND SLICING OF MATRIX**

In [38]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [42]:
arr[2,2]   # these are indexing

15

In [43]:
arr[2:5,4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

**BOOLEAN INDEXING**

In [44]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
bool_index = (arr%2==0)
bool_index
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
**NUMPY OPERATION**

**Arithmetic operations**

In [ ]:
import numpy as np

In [49]:
a1 = np.array([1,2,3,4])
b1 = np.array([4,5,6,7])

In [ ]:
a1+b1

In [ ]:
a1 - b1

In [ ]:
a1*b1

In [ ]:
a1/b1

In [50]:
a1//b1

array([0, 0, 0, 0])

In [ ]:
a1**b1

**Broadcasting**

In [51]:
arr= np.array([2,4,5,7,9])
arr

array([2, 4, 5, 7, 9])

In [52]:
arr +10  # this call broadcasting


array([12, 14, 15, 17, 19])

**Deep and shallow copy**

In [ ]:
# easy concept of python same as 

**matix operations**

In [ ]:
import numpy as np

In [53]:
A = np.array([[1,2,3,4],[2,4,1,3]])
B = np.array([[4,5,6,7],[5,2,7,8]])


In [54]:
A*B

array([[ 4, 10, 18, 28],
       [10,  8,  7, 24]])

In [58]:
A @ B.T

array([[60, 62],
       [55, 49]])

In [56]:
a=np.dot(A,B.T)
a

array([[60, 62],
       [55, 49]])

In [59]:
A.T  # for transpose


array([[1, 2],
       [2, 4],
       [3, 1],
       [4, 3]])

**Advance array manipulation**

**stacking array**

**stacking array does not work with array**

In [65]:
a= np.array([1,2,3,4])
b = np.array([5,6,8,9])

In [66]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 8, 9]])

In [67]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 8, 9])

In [68]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 8],
       [4, 9]])

**splitting array**

In [69]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [71]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [72]:
np.vsplit(c,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

**Excercise**

**valid sudoku**

In [74]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [75]:
np.sum(s,axis = 1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [76]:
b = np.sum(s,axis = 1)
b
for i in b:
    if i != 45:
        print(" sudoku is not valid for row")
        break
else:
    print(" it is valid for row")

 it is valid for row


In [77]:
np.sum(s, axis= 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [78]:
b = np.sum(s,axis = 0)
b
for i in b:
    if i != 45:
        print(" sudoku is not valid for columns")
        break
else:
    print(" it is valid for columns")

 it is valid for columns


In [83]:
# s[:3,:3].sum()
for i in range(0,9,3):
    for j in range(0,9,3) :
        print(f"{s[i:i+3,j:j+3]}") 

45

In [84]:
for i in range(0,9,3):
    for j in range(0,9,3) :
        print(f"{s[i:i+3,j:j+3].sum()}")

45
45
45
45
45
45
45
45
45


In [ ]:
import numpy as np

In [86]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [87]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [49]:
#Find the average age of students.
np.mean(data[:,0],axis = 0)

18.4

In [50]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [51]:
#Find the highest Science mark.
data[:,2].max()

95

In [52]:
#get the details of the student who scored more than 90 in math
data[data[:,1]>90]


array([[19, 92, 88]])

In [53]:
#Increase Math marks of all students by 5.
data[:,1] +5

array([90, 97, 81, 70, 95])

In [54]:
#Find how many students are younger than 19
(data[data[:,0] < 19])

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [55]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis =0)

array([81.6, 83.2])

In [56]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [88]:
#Replace all Science marks < 75 with 0.
data[:,2][(data[:,2] < 75)] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])